name = "loopic-net"
compatibility_date = "2024-09-13"

[env.production]
name = "loopic-net"

[[env.production.routes]]
pattern = "loopic.net/*"
zone_name = "loopic.net"

[[env.production.routes]]
pattern = "www.loopic.net/*"
zone_name = "loopic.net"
